Issue #559: Add '-warn all,noexternal' when compiling on 'rhel-8-icelake-64'
This removed this compilation error:
   error #8889: Explicit declaration of the EXTERNAL attribute is required