Issue #1072: Avoid using 'call abort()' since it is not standard
We replace with 'call utl_abort()'.

../modules/libmidas.a(bgckSSMIS_mod.f90.o): In function `__bgckssmis_mod_MOD_cld_filter_fweng':
src/modules/bgckSSMIS_mod.f90:693: undefined reference to `abort_'
collect2: error: ld returned 1 exit status