The variable 'ntotal' was declared as 'logical' instead of integer in routine 'n1qn3a' of module 'quasiNewton_mod'
modules/quasiNewton_mod.f90:867:21:

  867 |                   ps=ps/ntotal
      |                     1
Error: Operands of binary numeric operator ‘/’ at (1) are REAL(8)/LOGICAL(4)
src/modules/quasiNewton_mod.f90:875:28:

  875 |                   ps2=dsqrt(ps2/ntotal)
      |                            1
Error: Operands of binary numeric operator ‘/’ at (1) are REAL(8)/LOGICAL(4)