Issue #1058: Fix a 'type mismatch' warning in 'midasMpi_mod'
The module variable 'mmpi_maxTagValue' was used in a call to
'mpi_comm_get_attr' but it is not of the correct type.  The
documentation at
https://www.open-mpi.org/doc/v4.0/man3/MPI_Comm_get_attr.3.php is
suggesting to use 'integer(kind=MPI_ADDRESS_KIND)'.

A workaround is use a temporary variable of type
'integer(kind=MPI_ADDRESS_KIND)' and then cast it into the 'integer'
variable 'mmpi_maxTagValue'.

src/modules/midasMpi_mod.f90:125:84:

  125 |     call mpi_comm_get_attr(mpi_comm_world, mpi_tag_ub, mmpi_maxTagValue, flag, ierr)
      |                                                                                    1
Error: Type mismatch in argument ‘attribute_val’ at (1); passed INTEGER(4) to INTEGER(8)