Issue #1152: introduced user SSM for external libraries
does not compile:
```
Fatal Error: Cannot open module file ‘netcdf.mod’ for reading at (1): No
such file or directory
```

This error is related to the failing build of external libraries by
`ssm/package_external_libs`.  This will be delt with in #1163