Issue #1058: Using 'utl_abort' instead of built-in 'abort' routine
/home/erv000/data/midas/midas-1058-1/src/modules/obsErrors_mod.f90:2213:92:

 2213 |         if (obsIndex > obsCount) call abort('readOerFromObsFileForSW: Something went wrong')
      |                                                                                            1
Error: Too many arguments in call to ‘abort’ at (1)
/home/erv000/data/midas/midas-1058-1/src/modules/obsErrors_mod.f90:2239:94:

 2239 |           if (obsIndex > obsCount) call abort('readOerFromObsFileForSW: Something went wrong')
      |                                                                                              1
Error: Too many arguments in call to ‘abort’ at (1)
/home/erv000/data/midas/midas-1058-1/src/modules/obsErrors_mod.f90:2253:94:

 2253 |           if (obsIndex > obsCount) call abort('readOerFromObsFileForSW: Something went wrong')
      |                                                                                              1
Error: Too many arguments in call to ‘abort’ at (1)