Issue #1100: Bring some changes from 'main' for 'src/modules/interpolation_mod.f90' to be able to compile on HPCR-U3
The compilation was aborting on 'src/modules/interpolation_mod.f90'
with an internal error.  Chantal Pic suggested to incorporate the
changes made in the 'main' branch to satisfy GNU fortran.

Note that the code was compiling perfectly fine in debug mode.

The compilation error was:
    [ 33%] Building Fortran object src/modules/CMakeFiles/midas.dir/interpolation_mod.f90.o
              #0 0x0000000003310581
              #1 0x0000000003375357
              #2 0x0000000003375485
              #3 0x0000150e02e3e6f0
              #4 0x0000000002574a18
              #5 0x00000000025735db
              #6 0x000000000257316f
              #7 0x0000000002bf3cf1
              #8 0x0000000002bf3973
              #9 0x000000000236c21b
             #10 0x00000000024efa9b
             #11 0x00000000024ef553
             #12 0x00000000024e97f2
             #13 0x00000000032ae584
             #14 0x00000000032abde3
             #15 0x0000000003256111
             #16 0x0000000003433b58
             #17 0x0000150e02e29590
             #18 0x0000150e02e29640 __libc_start_main + 128
             #19 0x000000000308f0ee

    src/modules/interpolation_mod.f90: error #5633: **Internal compiler error: segmentation violation signal raised** Please report this error along with the circumstances in which it occurred in a Software Problem Report.  Note: File and line given may not be explicit cause of this error.
    compilation aborted for src/modules/interpolation_mod.f90 (code 3)
    make[1]: *** [src/modules/CMakeFiles/midas.dir/build.make:712: src/modules/CMakeFiles/midas.dir/interpolation_mod.f90.o] Error 3
    make: *** [Makefile:1360: interpolation_mod.f90.o] Error 2