Issue #799: We must specify where to find the SSM packages in 'ssm/publish' when installing.
Without this, it can abort because of this error message:
    Traceback (most recent call last):
      File "/fs/ssm/main/opt/ssm/ssm-11.7.1/ssm_11.7.1_all/lib/ssm.d/python/ssm_install.py", line 156, in run
        elif srcdir:
    UnboundLocalError: local variable 'srcdir' referenced before assignment
    error: operation failed