Issue #1058: Fix compilation error in 'localization_mod' where 'inout' was missing
/home/erv000/data/midas/midas-1058-1/src/modules/localization_mod.f90:268:36:

  268 |       call lsp_expandToMPIGlobal_r4(loc%lsp, cv_mpilocal, & ! IN
      |                                    1
Error: Dummy argument ‘loc’ with INTENT(IN) in pointer association context (actual argument to INTENT = OUT/INOUT) at (1)
/home/erv000/data/midas/midas-1058-1/src/modules/localization_mod.f90:245:33:

  245 |       call lsp_expandToMPIGlobal(loc%lsp, cv_mpilocal,  & ! IN
      |                                 1
Error: Dummy argument ‘loc’ with INTENT(IN) in pointer association context (actual argument to INTENT = OUT/INOUT) at (1)
/home/erv000/data/midas/midas-1058-1/src/modules/localization_mod.f90:221:35:

  221 |       call lsp_reduceToMPILocal_r4(loc%lsp,       & ! IN
      |                                   1
Error: Dummy argument ‘loc’ with INTENT(IN) in pointer association context (actual argument to INTENT = OUT/INOUT) at (1)
/home/erv000/data/midas/midas-1058-1/src/modules/localization_mod.f90:197:32:

  197 |       call lsp_reduceToMPILocal(loc%lsp,      & ! IN
      |                                1
Error: Dummy argument ‘loc’ with INTENT(IN) in pointer association context (actual argument to INTENT = OUT/INOUT) at (1)
/home/erv000/data/midas/midas-1058-1/src/modules/localization_mod.f90:152:24:

  152 |        call lsp_LsqrtAd(loc%lsp,       & ! IN
      |                        1
Error: Dummy argument ‘loc’ with INTENT(IN) in pointer association context (actual argument to INTENT = OUT/INOUT) at (1)
/home/erv000/data/midas/midas-1058-1/src/modules/localization_mod.f90:127:21:

  127 |       call lsp_Lsqrt(loc%lsp, controlVector, & ! IN
      |                     1
Error: Dummy argument ‘loc’ with INTENT(IN) in pointer association context (actual argument to INTENT = OUT/INOUT) at (1)